### ISSUE TITLE
个人建议

### ISSUE THREAD

**Issue by xiayy0328** [lixiang1994/VideoPlayer#1]
我觉得视频的控制层通过你的哪种方式创建话不太友好，控制层View和VC耦合太大了，后期处理旋转的话也比较麻烦，还是建议把视频控制层封装在一起做操作这样后期手势什么的可能比较好一点，也方便自定义。基础功能封装充分体现了Swift面向协议编程的思想，棒棒哒。

**Comment by lixiang1994** [comment]
哈哈, 感谢回复, 是这样的, 其实这个库只是提供player的封装, 如果这个库把view和player封在一起就丧失了通用性, demo中只是我比较提倡的一种思路, 正常来说 应该在自己项目中封装一套对于自身项目通用的view层或者view+player去使用, 这个完全是因人而异的封装, 所以应该交给使用者决定.

**Comment by lixiang1994** [comment]
其实你说"控制层View和VC耦合太大了"这点确实有, 但我个人觉得比 "view和player耦合太大" 更好一些, 因为每个页面(VC)都有自己的样式 View就应该是View, 从MVC的角度来看 View就应该只负责展示,  举个例子, 一个项目中可能有2种或3种播放页面, 样式完全不同. 这样我demo中的思路就可以很好地解决

**Comment by xiayy0328** [comment]
可能刚才我理解错了吧！我以为Demo里面提供的是一套默认的控制UI，所以才觉得那样不太合适。如果单纯的只是play功能封装的话就没有什么问题了。

**Comment by xiayy0328** [comment]
作者联系方式是什么？我加一下到时候可以交流一下。

**Comment by lixiang1994** [comment]
QQ: 332459523
